'''

This is the file that hosts the LLM. 
The LLM gets data from the processing file (ai.py) and uses it to evaluate the singing. 

'''

# !!!!!!! TO DO !!!!!!!
# Insert the model located in karaoke_classifier.py into this file (in place of TinyLlama)
# :)

# importing libraries
# re allows the answer generated by the llm to be more concise
# transformers library provides the llm
# torch gives device management and hopefully provides machine learning capabilities
# audio gives the AudioProcessor class

import re
from transformers import pipeline
import torch
import audio
from karaoke_classifier import KaraokeClassifier

class PromptManager:
    '''
    The PromptManager class provides the prompts for the LLM to evaluate singing performance.
    It receives both audio-derived measurements and, when available, the dataset classifier score.
    '''

    # The model used for text generation is TinyLlama. 

    __MODEL = "TinyLlama/tinyllama-1.1B-Chat-v1.0"

    # Device management done with torch. 
    # Tries to use bfloat16 if CUDA is available, otherwise uses float32.

    pipe_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

    # Generates the text generation model

    def __init__(self):
        self.generate = pipeline(
            task="text-generation",
            model=self.__MODEL,
            dtype=self.pipe_dtype,
            device_map=None,
            trust_remote_code=True,
        )
        self.audio_processor = audio.AudioProcessor()
        self.classifier = KaraokeClassifier()

    def evaluate_song(self, audio_path, message):
        try:
            audio_analysis = self.audio_processor.process_audio(audio_path)
            metrics = self.audio_processor.evaluate_audio_metrics(audio_path)

            dataset_grade, dataset_confidence = self.classifier.estimate_standalone_grade(audio_path)
            if self.classifier.dataset_model is not None:
                try:
                    dataset_grade, dataset_confidence = self.classifier.predict_grade(audio_path)
                except Exception:
                    dataset_grade, dataset_confidence = self.classifier.estimate_standalone_grade(audio_path)

            standalone_grade, standalone_confidence = self.classifier.estimate_standalone_grade(audio_path)
        except Exception as exc:
            return f"Error occurred while processing audio: {exc}"

        prompt = (
            f"User description: {message}\n\n"
            f"Approximate dataset-model grade: {dataset_grade}\n"
            f"Dataset confidence: {dataset_confidence:.2f}\n\n"
            f"Approximate standalone heuristic grade: {standalone_grade}\n"
            f"Standalone confidence: {standalone_confidence:.2f}\n\n"
            f"Audio metrics:\n"
            f"- pitch score: {metrics['pitch_score']}\n"
            f"- beat score: {metrics['beat_score']}\n"
            f"- clarity score: {metrics['clarity_score']}\n"
            f"- consistency score: {metrics['consistency_score']}\n\n"
            f"Transcript:\n{audio_analysis['transcript']}\n\n"
            f"Pitch statistics:\n{audio_analysis['pitch_statistics']}\n\n"
            "Important: there is no reference melody or exact note target. Treat both scores as rough indicators of tonal stability and vocal control, not precise pitch-accuracy measurements.\n\n"
            "Give a concise but helpful karaoke evaluation. Include:\n"
            "1. an overall verdict\n"
            "2. what the singer did well\n"
            "3. three specific improvements\n"
            "4. a brief explanation of how the audio metrics and rough score sources support the verdict\n"
            "5. a sentence stating that the score is approximate because there is no reference melody."
        )

        result = self.generate(
            [
                {"role": "system", "content": "You are an expert karaoke coach and music evaluator."},
                {"role": "user", "content": prompt},
            ],
            max_new_tokens=400,
            do_sample=False,
            repetition_penalty=1.1,
            no_repeat_ngram_size=4,
        )

        # the response is transformed into a string
        answer = result[0]["generated_text"]
        if isinstance(answer, list):
            answer = answer[-1].get("content", "")
        elif not isinstance(answer, str):
            answer = str(answer)

        # intended to make a cleaner answer
        sentences = re.split(r"(?<=[.!?])\s+", answer.strip())
        cleaned_sentences = []
        for sentence in sentences:
            if not cleaned_sentences or sentence != cleaned_sentences[-1]:
                cleaned_sentences.append(sentence)
        return " ".join(cleaned_sentences)

    def prompt(self):
        message = input("Describe your karaoke performance: ")
        audio_path = input("Path to the audio file: ")
        return self.evaluate_song(audio_path, message)
